# Generated by Django 3.0.5 on 2020-05-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='catgory',
            new_name='category',
        ),
        migrations.AddField(
            model_name='statusvenue',
            name='booked',
            field=models.BooleanField(default=True),
        ),
    ]
