# Generated by Django 3.0.5 on 2020-05-04 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_organisation_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='user',
        ),
        migrations.AddField(
            model_name='venue',
            name='organisation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='event.Organisation'),
            preserve_default=False,
        ),
    ]
