# Generated by Django 3.0.5 on 2020-05-04 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0004_auto_20200504_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='GOH',
            field=models.CharField(default='admin', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='MC',
            field=models.CharField(default='me', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='dressCode',
            field=models.CharField(default='b/w', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='paybillNumber',
            field=models.BigIntegerField(default=111111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='ticketFee',
            field=models.BigIntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
