# Generated by Django 3.0.5 on 2020-06-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200630_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='active',
            field=models.CharField(default='true', max_length=5),
        ),
    ]
