# Generated by Django 3.0.5 on 2020-05-04 11:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200504_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusvenue',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statusvenue',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='statusvenue',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='event.Venue'),
        ),
    ]
