# Generated by Django 3.0.8 on 2020-07-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20200630_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(null=True)),
                ('amount', models.BigIntegerField(null=True)),
                ('MpesaReceipt', models.CharField(max_length=30, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('checkoutRequestId', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=10)),
                ('direction', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticketNumber',
            field=models.CharField(max_length=50),
        ),
    ]
