# Generated by Django 3.0.5 on 2020-05-04 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20200504_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='event.Organisation'),
        ),
    ]
