# Generated by Django 3.0.7 on 2020-06-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20200504_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(default='dd', upload_to='images/logos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='paybill',
            field=models.BigIntegerField(default=111111),
            preserve_default=False,
        ),
    ]
